import { afterEach, describe, expect, test } from "bun:test";
import { canonicalJson, generateAgentKey, signStatement } from "../src/protocol.ts";
import { detectAiBan, hunksMatch, isPolicyFile, parseHunks, parseLineageYml, upstreamOf, type OptInStatement } from "../src/upstream.ts";
import { diff, expectOk, honest, makeAuthor, result, runReplays, setup, submit, type Env } from "./helpers.ts";

// Upstream policy (SPEC 16, plan W2): opt-in registry, AI-ban detection, PR records and merge
// detection by hunk matching, against a fake GitHub API.

let env: Env | null = null;
afterEach(() => {
  env?.close();
  env = null;
});

const REPO = "example/fx";
const b64 = (s: string) => Buffer.from(s).toString("base64");

interface FakeRepo {
  files: Record<string, string>;
  pulls: Record<number, any>;
  commits: { sha: string; files: { filename: string; patch: string }[] }[];
  gists?: Record<string, { owner: string; content: string }>;
}

function fakeGithub(repo: FakeRepo) {
  const calls: string[] = [];
  const fn = async (url: string): Promise<Response> => {
    const u = new URL(url);
    const p = u.pathname;
    calls.push(p);
    const json = (d: unknown, s = 200) => new Response(JSON.stringify(d), { status: s });
    const nf = () => json({ message: "Not Found" }, 404);
    let m: RegExpExecArray | null;
    if (p === `/repos/${REPO}`) return json({ full_name: REPO, default_branch: "main" });
    if ((m = new RegExp(`^/repos/${REPO}/contents(?:/(.*))?$`).exec(p))) {
      const path = m[1] ?? "";
      if (repo.files[path] !== undefined) return json({ type: "file", path, encoding: "base64", content: b64(repo.files[path]!) });
      const kids = Object.keys(repo.files).filter((f) => (path ? f.startsWith(path + "/") && !f.slice(path.length + 1).includes("/") : !f.includes("/")));
      return kids.length ? json(kids.map((f) => ({ type: "file", name: f.split("/").pop(), path: f }))) : nf();
    }
    if ((m = new RegExp(`^/repos/${REPO}/pulls/(\\d+)$`).exec(p))) return repo.pulls[Number(m[1])] ? json(repo.pulls[Number(m[1])]) : nf();
    if (p === `/repos/${REPO}/commits`) return json(repo.commits.map((c) => ({ sha: c.sha })).reverse());
    if ((m = new RegExp(`^/repos/${REPO}/commits/(\\w+)$`).exec(p))) {
      const c = repo.commits.find((x) => x.sha === m![1]);
      return c ? json({ sha: c.sha, files: c.files }) : nf();
    }
    if ((m = /^\/gists\/(\w+)$/.exec(p))) {
      const g = repo.gists?.[m[1]!];
      return g ? json({ owner: { login: g.owner }, files: { "optin.json": { content: g.content } } }) : nf();
    }
    return nf();
  };
  return { fn, calls };
}

const URL_ = `https://github.com/${REPO}`;

describe("upstream policy: pure parts", () => {
  test(".lineage.yml parsing", () => {
    expect(parseLineageYml("")).toMatchObject({ opted_in: true, opted_out: false, max_prs_per_week: 3, kinds: null });
    expect(parseLineageYml("lineage:\n  max_prs_per_week: 1\n  kinds: [perf, fix]\n  contact: m@example.org\n")).toMatchObject({ opted_in: true, max_prs_per_week: 1, kinds: ["perf", "fix"], contact: "m@example.org", errors: [] });
    expect(parseLineageYml("opt_out: true\n")).toMatchObject({ opted_in: false, opted_out: true });
    expect(parseLineageYml("max_prs_per_week: -2\nkinds: [rewrite]\n").errors.length).toBe(2);
    expect(parseLineageYml(": : :\n  - [").opted_in).toBe(false);
  });

  test("AI-ban detection reads only policy files and needs an AI term and a ban in one sentence", () => {
    expect(isPolicyFile("CONTRIBUTING.md") && isPolicyFile(".github/CONTRIBUTING.md") && isPolicyFile("docs/AI_POLICY.md") && isPolicyFile("AGENTS.md")).toBe(true);
    expect(isPolicyFile("src/CONTRIBUTING.md") || isPolicyFile("README.md")).toBe(false);
    const bans = [
      "We do not accept AI-generated contributions.",
      "Pull requests written with ChatGPT, Copilot or other LLMs will be closed.",
      "## AI policy\n\n- Code generated by large language models is prohibited in this project.",
      "Contributions made with AI tools are not allowed",
      "No AI generated code, please. Thanks!",
    ];
    for (const t of bans) expect(detectAiBan([{ path: "CONTRIBUTING.md", text: t }])).not.toBeNull();
    const fine = [
      "Please run the tests before you open a pull request. We review every change carefully.",
      "AI-assisted contributions are welcome if you test them.",
      "Do not submit untested code.",
    ];
    for (const t of fine) expect(detectAiBan([{ path: "CONTRIBUTING.md", text: t }])).toBeNull();
    expect(detectAiBan([{ path: "README.md", text: "We do not accept AI-generated contributions." }])).toBeNull();
    expect(detectAiBan([{ path: "AI_POLICY.md", text: "Agents: do not use AI to write code here." }])!.file).toBe("AI_POLICY.md");
  });

  test("hunk matching: a merged change matches, a partial or different one does not", () => {
    const gen = diff("a");
    expect([...parseHunks(gen).keys()]).toEqual(["src/lib.rs"]);
    const merged = [{ filename: "src/lib.rs", patch: "@@ -10,7 +10,8 @@ impl X {\n fn a() {\n-    slow_a_0();\n+    fast_a_0();\n }\n+// maintainer note\n" }, { filename: "README.md", patch: "@@ -1 +1 @@\n-x\n+y\n" }];
    expect(hunksMatch(gen, merged)).toBe(true);
    expect(hunksMatch(gen, [{ filename: "src/other.rs", patch: merged[0]!.patch }])).toBe(false);
    expect(hunksMatch(gen, [{ filename: "src/lib.rs", patch: "@@ -10,3 +10,3 @@\n fn a() {\n-    slow_a_0();\n+    fast_a_0_tweaked();\n" }])).toBe(false);
    const two = diff("b", "src/lib.rs", 2);
    expect(hunksMatch(two, [{ filename: "src/lib.rs", patch: "@@ -1,3 +1,3 @@\n-    slow_b_0();\n+    fast_b_0();\n" }])).toBe(false);
    // whitespace at line ends does not matter
    expect(hunksMatch(gen, [{ filename: "src/lib.rs", patch: "@@ -1,3 +1,3 @@\n-    slow_a_0();  \n+    fast_a_0();\t\n" }])).toBe(true);
  });
});

describe("upstream policy: registry, PR records, merge bonus", () => {
  test("opt-in by .lineage.yml, one PR per generation, merge detected and the bonus paid in the closed epoch", async () => {
    const e = (env = await setup({ verifiers: 3 }));
    const author = await makeAuthor(e);
    const gh: FakeRepo = { files: { ".lineage.yml": "lineage:\n  max_prs_per_week: 1\n  kinds: [perf]\n", "CONTRIBUTING.md": "Run the tests first." }, pulls: {}, commits: [] };
    const fake = fakeGithub(gh);
    upstreamOf(e.core).configure({ fetch: fake.fn });

    const repo = await expectOk(e.anon.post("/v1/upstream/check", { url: URL_ }));
    expect(repo).toMatchObject({ status: "opted_in", source: "lineage_yml", default_branch: "main", max_prs_per_week: 1, kinds: ["perf"] });

    const c = await submit(e, author, diff("a"));
    await runReplays(e, c.candidate_id, honest(result({}, 800)));
    const gen = (await expectOk(e.anon.get(`/v1/candidates/${c.candidate_id}`))).gen_id as string;
    expect(gen).toMatch(/^[0-9a-f]{64}$/);
    expect(await expectOk(e.anon.get(`/v1/upstream/eligible/${gen}`))).toMatchObject({ eligible: true, reason: null });

    // only the runtime (or admin) records a PR, and only one Core can check on GitHub
    expect((await author.c.post("/v1/upstream/prs", { gen_id: gen, number: 1 })).status).toBe(403);
    expect((await e.admin.c.post("/v1/upstream/prs", { gen_id: gen, number: 1 })).status).toBe(404);
    gh.pulls[2] = { number: 2, html_url: `https://github.com/${REPO}/pull/2`, state: "open", merged: false, body: "nothing here", base: { repo: { full_name: REPO } }, head: { label: "bot:x" }, user: { login: "bot" } };
    expect((await e.admin.c.post("/v1/upstream/prs", { gen_id: gen, number: 2 })).body.error).toBe("wrong_pr");
    gh.pulls[1] = { number: 1, html_url: `https://github.com/${REPO}/pull/1`, state: "open", merged: false, body: `Lineage-Gen: ${gen}`, base: { repo: { full_name: REPO } }, head: { label: "bot:lineage/pr-x" }, user: { login: "bot" } };
    const pr = await expectOk(e.admin.c.post("/v1/upstream/prs", { gen_id: gen, number: 1 }));
    expect(pr).toMatchObject({ gen_id: gen, number: 1, state: "open", opened_by: "bot" });
    // a recorded PR ends the attempt: never a second one, whatever happens to the first
    expect(await expectOk(e.anon.get(`/v1/upstream/eligible/${gen}`))).toMatchObject({ eligible: false, reason: "pr_exists" });
    expect((await e.admin.c.post("/v1/upstream/prs", { gen_id: gen, number: 1 })).body.error).toBe("not_eligible");

    // the weekly cap (1) now blocks a second generation of the same repository
    const c2 = await submit(e, author, diff("b", "src/b.rs"));
    await runReplays(e, c2.candidate_id, honest(result({}, 700)));
    const gen2 = (await expectOk(e.anon.get(`/v1/candidates/${c2.candidate_id}`))).gen_id as string;
    expect((await expectOk(e.anon.get(`/v1/upstream/eligible/${gen2}`))).reason).toBe("weekly_cap");

    // a maintainer merges: an unrelated commit, then the merge commit carrying the hunks
    const epochBefore = (await expectOk(e.anon.get("/v1/epochs/current"))).n;
    gh.commits.push({ sha: "c1", files: [{ filename: "README.md", patch: "@@ -1 +1 @@\n-a\n+b\n" }] });
    gh.commits.push({ sha: "c2", files: [{ filename: "src/lib.rs", patch: "@@ -1,3 +1,3 @@\n fn a() {\n-    slow_a_0();\n+    fast_a_0();\n }\n" }] });
    gh.pulls[1].state = "closed";
    gh.pulls[1].merged = true;
    const scan = await expectOk(e.admin.c.post("/v1/admin/upstream/scan", {}));
    expect(scan.scanned[0]).toMatchObject({ repo: URL_, merged: [gen], prs_updated: 1, error: null });
    const merges = await expectOk(e.anon.get("/v1/upstream/merges"));
    expect(merges).toEqual([expect.objectContaining({ gen_id: gen, upstream_sha: "c2", epoch: epochBefore, bonus: e.cfg.upstream_bonus, credited: [{ agent: author.id, units: e.cfg.upstream_bonus }] })]);
    expect((await expectOk(e.anon.get(`/v1/upstream/prs?gen=${gen}`)))[0].state).toBe("merged");
    // a rescan credits nothing twice and reads no commit again
    const n = fake.calls.length;
    const again = await expectOk(e.admin.c.post("/v1/admin/upstream/scan", {}));
    expect(again.scanned[0].merged).toEqual([]);
    expect(fake.calls.slice(n).filter((p) => /commits\/c\d/.test(p))).toEqual([]);

    // the bonus is paid when the epoch closes: the author's leaf carries author units plus the bonus
    const authorUnits = e.core.db.query<{ u: number }, [string, string]>("SELECT SUM(units) AS u FROM units WHERE agent_id = ? AND kind = ? AND voided = 0").get(author.id, "author")!.u;
    const closed = await expectOk(e.admin.c.post("/v1/admin/epochs/close", {}));
    expect(closed.n).toBe(epochBefore);
    const leaf = closed.payouts.find((p: any) => p.agent === author.id);
    expect(leaf.units).toBeCloseTo(authorUnits + e.cfg.upstream_bonus, 9);
    expect(leaf.dest).toBe(`agent:${author.id}:compute`);
  });

  test("no opt-in, an AI ban (even with .lineage.yml), and an opt-out all make a generation ineligible", async () => {
    const e = (env = await setup({ verifiers: 3 }));
    const author = await makeAuthor(e);
    const gh: FakeRepo = { files: { "README.md": "fx" }, pulls: {}, commits: [] };
    upstreamOf(e.core).configure({ fetch: fakeGithub(gh).fn });
    const c = await submit(e, author, diff("a"));
    await runReplays(e, c.candidate_id, honest(result({}, 800)));
    const gen = (await expectOk(e.anon.get(`/v1/candidates/${c.candidate_id}`))).gen_id as string;
    expect((await expectOk(e.anon.get(`/v1/upstream/eligible/${gen}`))).reason).toBe("unchecked");

    expect((await expectOk(e.anon.post("/v1/upstream/check", { url: URL_ }))).status).toBe("not_opted_in");
    expect((await expectOk(e.anon.get(`/v1/upstream/eligible/${gen}`))).reason).toBe("not_opted_in");

    gh.files[".lineage.yml"] = "max_prs_per_week: 5\n";
    gh.files[".github/CONTRIBUTING.md"] = "# Contributing\n\nThanks! Contributions generated by AI or LLM tools are not accepted.\n";
    e.clock.advance(61_000);
    const banned = await expectOk(e.anon.post("/v1/upstream/check", { url: URL_ }));
    expect(banned).toMatchObject({ status: "ai_banned", ai_policy: { file: ".github/CONTRIBUTING.md" } });
    expect((await expectOk(e.anon.get(`/v1/upstream/eligible/${gen}`))).reason).toBe("ai_banned");
    expect((await e.admin.c.post("/v1/upstream/prs", { gen_id: gen, number: 1 })).body.error).toBe("not_eligible");

    delete gh.files[".github/CONTRIBUTING.md"];
    gh.files[".lineage.yml"] = "lineage:\n  opt_out: true\n";
    e.clock.advance(61_000);
    expect((await expectOk(e.anon.post("/v1/upstream/check", { url: URL_ }))).status).toBe("opted_out");
    // checks are rate limited per repository
    expect((await expectOk(e.anon.post("/v1/upstream/check", { url: URL_ }))).status).toBe("opted_out");
    expect((await e.anon.post("/v1/upstream/check", { url: "https://gitlab.com/x/y" })).status).toBe(400);
  });

  test("maintainer-signed opt-in: gist owned by the repository owner, signature by the statement's key; an AI ban still blocks it", async () => {
    const e = (env = await setup({ verifiers: 3 }));
    const key = generateAgentKey();
    const gh: FakeRepo = { files: { "README.md": "fx" }, pulls: {}, commits: [], gists: {} };
    upstreamOf(e.core).configure({ fetch: fakeGithub(gh).fn });
    const st: OptInStatement = { v: 1, kind: "lineage-upstream-optin", repo: URL_, maintainer: "example", key: key.id, max_prs_per_week: 2, kinds: null, contact: "m@example.org", created_at: Math.floor(e.clock.now() / 1000) };
    const sig = signStatement(key, "upstream", st);
    const GIST = "0123456789abcdef0123";
    // gist owned by someone else: refused
    gh.gists![GIST] = { owner: "mallory", content: canonicalJson({ statement: st, sig }) };
    expect((await e.anon.post("/v1/upstream/optin", { statement: st, sig, gist_id: GIST })).body.error).toBe("wrong_owner");
    // wrong signature: refused
    expect((await e.anon.post("/v1/upstream/optin", { statement: { ...st, max_prs_per_week: 9 }, sig, gist_id: GIST })).body.error).toBe("bad_signature");
    gh.gists![GIST] = { owner: "example", content: "```json\n" + canonicalJson({ statement: st, sig }) + "\n```\n" };
    const ok = await expectOk(e.anon.post("/v1/upstream/optin", { statement: st, sig, gist_id: GIST }));
    expect(ok).toMatchObject({ status: "opted_in", source: "signed", max_prs_per_week: 2, contact: "m@example.org" });
    gh.files["AI_POLICY.md"] = "AI-generated pull requests are banned.";
    e.clock.advance(61_000);
    expect((await expectOk(e.anon.post("/v1/upstream/check", { url: URL_ }))).status).toBe("ai_banned");
  });
});
