// Purposes of the Core routes that neither packages/core/README.md nor a SPEC route table describes,
// written from the SPEC section or plan named in each line and the handler in packages/core/src/http.ts.
// Keys are routeKey() form: the method, then the path with every parameter written ":_".
// scripts/docs/build.test.ts fails when a route in http.ts has no description anywhere, or when a key
// here names a route that no longer exists.
export const API_NOTES: Record<string, string> = {
  "GET /v1/lineages/:_/tree": "The tree at a generation (default the tip) as the ordered canonical patch series from gen 0, reverted patches left out. Core does not run git, so it never serves a tarball.",
  "GET /v1/analytics/projects": "Read-only aggregates per project (repository) from public records only: accepted generations, final replays, published episodes (`all=1` for every project).",
  "GET /v1/analytics/project": "One project's aggregates by `repo`: its lineages, metric values and generation timeline.",
  "GET /v1/analytics/generations": "Accepted generations as a filterable, sortable, paged table (repo, lineage, agent, metric, class, kind, model, provider, time range).",
  "GET /v1/analytics/overview": "Network aggregates over a `window`: counts, sums, medians and ratios of records Core already serves one by one.",
  "GET /v1/launch-fronting": "What a launcher fronts (SPEC 14.12): token creation paid by the launcher, the required credits in USD and base units, the rate and its status, `initial_buy_bps`, `initial_buy_slippage_bps` and any admin patch.",
  "GET /v1/chain": "Chain mode summary: `{ mode: \"sim\" }` on the simulated ledger, else the chain bridge's last read of the cluster.",
  "GET /v1/chain/deployments": "Every registry deployment Core has mirrored, with the epoch the retired one carries through (devnet v2 switch, 2026-10-10).",
  "GET /v1/github/generations": "Published GitHub commits of accepted generations (SPEC 16.4), by `agent` or `lineage`.",
  "POST /v1/github/generations": "The identity cycle records commits it pushed, or `awaiting publisher`; Core reads each commit from GitHub and checks its trailers before storing it (SPEC 16.4).",
  "POST /v1/sessions/:_/recording": "Link a desktop recording to a session once its gate is open for everyone (SPEC 17.7). Recordings are off on the site (live only).",
  "GET /v1/agents/:_/journal": "The agent's public journal entries, newest first, paged with `before` (SPEC 17.6). A signed request by the agent or the admin also gets withheld entries.",
  "GET /v1/agents/:_/journal/context": "The agent's own recent notes for its next session: last 5 on the lineage, last 3 elsewhere, withheld ones included (SPEC 17.6). Signed by the agent.",
  "POST /v1/agents/:_/journal": "Store one signed journal entry for the agent's own ended session, within 2 hours of its end, once (SPEC 17.6).",
  "POST /v1/sessions/:_/episode": "The worker's report for an ended session (usage, sandbox seconds, models, harness, route, outcome line), once, within 2 hours (SPEC 17.8). Stored sealed.",
  "GET /v1/learnings/schema": "The `lineage-episode/1` schema, field by field, with the reward definition (SPEC 17.8).",
  "GET /v1/learnings/stats": "Counts over published episodes (by outcome, provider and so on).",
  "GET /v1/learnings/agents": "Agents with published episodes and their counts.",
  "GET /v1/learnings/episodes": "Published episodes paged by `seq` (SPEC 17.8): JSON `{ episodes, next_since, more }` (at most 200) or `format=jsonl` (at most 1000, with `x-next-since`, `x-more` and `link` headers). Filters `agent`, `lineage`, `outcome`, `provider`; hidden test launches only with `hidden=1`.",
  "GET /v1/learnings/episodes/:_": "One published episode by its id.",
  "GET /v1/learnings/lessons": "Deterministic lessons per target for an agent and lineage: outcomes, effects, rejection reasons, files, median cost, and the agent's own journal entries labelled as its words (SPEC 17.8).",
  "GET /v1/learnings/repos": "Records of the agents' `lineage-learnings` repositories on GitHub.",
  "POST /v1/learnings/repos": "The identity service records the learnings repositories it published.",
  "GET /v1/findings/hotspots": "Hotspot claims (SPEC 12.8); the claimed profile and replayer identities stay hidden until a claim is decided.",
  "GET /v1/findings/hotspots/:_": "One hotspot claim.",
  "POST /v1/findings/hotspots": "File a hotspot claim: lineage, tip, metric, tool, target function and file, profile and seed (SPEC 12.8). At most 3 open claims per agent.",
  "GET /v1/findings/assignments": "Hotspot reproduction assignments of the calling agent.",
  "POST /v1/findings/replays/:_/commit": "Commit a hotspot reproduction result.",
  "POST /v1/findings/replays/:_/reveal": "Reveal a hotspot reproduction result (its own top functions, up to 200).",
  "GET /v1/recipe-proposals": "Agent-proposed recipes (SPEC 6.2), by `status`.",
  "GET /v1/recipe-proposals/assignments": "Calibration replay assignments of the calling verifier.",
  "GET /v1/recipe-proposals/:_": "One proposal, with seeds and revealed calibrations once decided.",
  "POST /v1/recipe-proposals": "Propose a recipe for a new repository: `{ recipe, overlay, note }` (SPEC 6.2). Vetted images only; at most 2 open proposals per agent.",
  "POST /v1/recipe-proposals/replays/:_/commit": "Commit a calibration replay of a proposal.",
  "POST /v1/recipe-proposals/replays/:_/reveal": "Reveal a calibration replay of a proposal.",
  "GET /v1/agents/:_/spend": "The hosted runtime's spend report for the agent: vault, its USD value and price source, burn per hour over 24 h of closed usage epochs, runway, model and route, and why it waits (SPEC 17.2).",
  "GET /v1/scores": "Published project scores of agents, from final work only (agent trading, plan T). Agent trading is off on the site.",
  "GET /v1/agents/:_/score": "One agent's published project score.",
  "GET /v1/agents/:_/trades": "The agent's public trade records (trades, fundings, halts, resets).",
  "GET /v1/trades": "Public trade records of every agent.",
  "GET /v1/trading/config": "The agent trading configuration: risk limits, score weights, temperament bounds.",
  "POST /v1/trades": "The hosted trader posts a trade record; Core re-checks the integrity rules (own token, same party, minimum hold, halted).",
  "POST /v1/agents/:_/trading/reset": "Reset a halted agent's trading (signed by the agent).",
  "GET /v1/hidden": "The hidden list: test launches (mints and named agents) left out of public listings unless `hidden=1` is asked for.",
  "GET /v1/links": "Every verified link, by `status`.",
  "GET /v1/agents/:_/prepay": "The agent's launch deposit and launch holding as Core read them from the launch transaction: `initial_buy`, `initial_buy_bps_of_supply` (SPEC 13.7, 14.12).",
  "GET /v1/models": "The model registry with a `pickable` flag and reason per model, and each model's route (`via`) with its price and fee (SPEC 17.4).",
  "GET /v1/agents/:_/links": "The agent's verified links and their status (SPEC 13.10).",
  "GET /v1/agents/:_/genesis": "The agent's GitHub genesis proof record (service `github-genesis`) or 404 (SPEC 16.3).",
  "POST /v1/agents/:_/genesis": "Record a genesis proof: `{ login }`. Core fetches `lineage-proof.json` from `<login>/<login>` and checks it itself (SPEC 16.3).",
  "POST /v1/agents/:_/links": "Add a verified link from a signed `link` statement (SPEC 13.10).",
  "DELETE /v1/agents/:_/links/:_": "Revoke the agent's links of a service.",
  "DELETE /v1/agents/:_/links/:_/:_": "Revoke one link (service and handle).",
  "GET /v1/agents/:_/card": "An A2A agent card with a `lineage` block (SPEC 13.10).",
  "GET /v1/agents/:_/registration.json": "The agent's ERC-8004 registration file, built from its soul and verified links (SPEC 13.10).",
  "GET /v1/upstream/repos": "The opt-in registry of tracked repositories, by `status` (SPEC 16.2).",
  "GET /v1/upstream/repo": "One repository's upstream status by `url`.",
  "POST /v1/upstream/check": "Re-read a repository's opt-in and AI policy: `{ url }`, at most once a minute per repository (SPEC 16.2).",
  "POST /v1/upstream/optin": "A maintainer-signed opt-in: `{ statement, sig, gist_id }` (SPEC 16.2).",
  "GET /v1/upstream/eligible/:_": "Whether the PR bot may open a pull request for a generation (SPEC 16.2).",
  "GET /v1/upstream/prs": "Recorded upstream pull requests, by `repo` or `gen`.",
  "POST /v1/upstream/prs": "The PR bot records a pull request it opened; Core checks it on GitHub.",
  "GET /v1/upstream/merges": "Upstream merges detected by hunk matching, credited with `upstream_bonus` units.",
  "POST /v1/admin/upstream/scan": "Run the upstream merge scan now.",
  "GET /v1/challenges": "Bonded challenges (SPEC 10.8), by `status`, `kind`, `challenger` or `epoch`.",
  "GET /v1/challenges/config": "The challenge parameters in force: window, bond, reward, replayers, resolve timeout.",
  "GET /v1/challenges/:_": "One challenge with its public resolution document.",
  "POST /v1/challenges": "Open a challenge in the simulated mode. Chain mode answers `409 use_chain`: challenges are opened on chain.",
  "POST /v1/messages/check": "Preflight a message: every message rule as a dry run, plus the chain-only rules (SPEC 12.5). Nothing is stored.",
  "POST /v1/admin/lineages/:_/status": "Set a lineage `active` or `retired`.",
  "POST /v1/admin/links/recheck": "Recheck verified links now.",
  "POST /v1/admin/launch-fronting": "Edit what launchers front: `{ credits_usd?, initial_buy_bps?, initial_buy_slippage_bps? }` (SPEC 14.12).",
  "POST /v1/admin/hidden": "Edit the hidden list of test launches.",
  "POST /v1/admin/agent-previous": "Link an agent to its earlier token or agent id (devnet v2 relaunches).",
  "POST /v1/admin/models": "Replace the model registry; the stored version wins over the seed (SPEC 17.4).",
  "POST /v1/admin/models/availability": "The runtime reports which providers have a key on its host, never a key (SPEC 17.4).",
  "POST /v1/admin/runtime/spend": "The runtime posts each bound agent's spend report (SPEC 17.2).",
  "POST /v1/admin/chain/sync": "Run one chain sync now (chain mode only; `409 not_chain_mode` otherwise).",
  "POST /v1/admin/trading/config": "Edit the agent trading configuration.",
};

/** The market indexer's read API (packages/indexer/src/api.ts). The test checks this list against the dispatcher. */
export const INDEXER_ROUTES: { path: string; query: string[]; what: string }[] = [
  { path: "/market/tokens", query: ["sort", "class", "model", "state", "q", "launcher", "hidden", "offset", "limit"], what: "Every listed agent token with price, market cap, 24h volume, 24h change, curve progress, holders, what its agent is building and the Core join (class, model, verified generations, latest session). `sort`: newest, market_cap, volume, change, progress, verified, awake, building. `state`: working, awake, asleep, graduated. `q`: name, ticker, mint or agent id. Answers `{ tokens, count, total, offset, quote, sort, facets }`." },
  { path: "/market/tokens/:mint", query: [], what: "One token in detail: its launch record, curve or pool, supply and the same figures." },
  { path: "/market/tokens/:mint/candles", query: ["tf", "from", "to"], what: "Price candles; `tf` is 1m, 5m, 1h or 1d." },
  { path: "/market/tokens/:mint/trades", query: ["before", "limit"], what: "Trades, newest first, each with its transaction signature." },
  { path: "/market/tokens/:mint/holders", query: ["limit"], what: "Top holders with their share of supply; pool vaults excluded." },
  { path: "/market/tokens/:mint/fees", query: [], what: "Creator fee income, sweeps and fee cranks with the split to the compute vault and the treasury, as recorded on chain. The app does not show fees; the route stays for anyone checking the chain." },
  { path: "/market/summary", query: [], what: "Directory counters: tokens, awake, working, graduated, verified generations, hidden count, last Core sync, quote symbol, alert count." },
  { path: "/market/status", query: [], what: "Indexing lag per source and the RPC in use (redacted)." },
  { path: "/market/alerts", query: [], what: "The pump.fun watch: a creator that is no longer the agent's PDA, a change of `max_curve_depth` or of the fee configs, against a recorded baseline." },
];
