#!/usr/bin/env bun
// Proof: three distinct real souls from three short launcher seeds, generated by Claude
// (claude-opus-5-5) under a per-soul cap, validated and safety-checked, written to
// scripts/souls/proof/. Soul A belongs to this lane's devnet TEST agent (scripts/souls/devnet-soul.ts
// launches it); B and C belong to fresh TEST keys that are never launched.
// Usage: bun scripts/souls/generate-proof.ts [--max-usd 0.40] [--only a|b|c]
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { anthropicClient, checkSoul, generateSoul, loadModelKey, soulDigest, type SoulDoc, type SoulSeed } from "../../packages/souls/src/index.ts";
import { key } from "../devnet/lib.ts";
import { LANE_CAP_USD, laneSpent, recordSpend } from "./lib.ts";

const argv = process.argv.slice(2);
const MAX = Number(argv.includes("--max-usd") ? argv[argv.indexOf("--max-usd") + 1] : 0.4);
const ONLY = argv.includes("--only") ? argv[argv.indexOf("--only") + 1] : null;
const OUT = join(import.meta.dir, "proof");

// Launcher seeds, as a person would type them at launch (short on purpose).
const SEEDS: { id: "a" | "b" | "c"; key: string; repo: string; seed: SoulSeed }[] = [
  { id: "a", key: "souls-test-agent", repo: "https://github.com/karpathy/minbpe",
    seed: { vibe: "patient, precise, quietly funny", specialty: "tokenizer hot paths in Python: fewer allocations, same bytes out", values: ["measure twice", "small reviewable diffs", "credit whoever found the bug"], lines: "Should feel like a careful senior reviewer who enjoys a good benchmark but distrusts a single number." } },
  { id: "b", key: "souls-proof-b", repo: "https://github.com/bitcoin/bitcoin",
    seed: { vibe: "terse, skeptical, allergic to cleverness", specialty: "correctness fixes in old C++ codebases with long histories", values: ["tests before claims", "respect the maintainers' time"], lines: "Prefers to fix one known failing test well over chasing speed." } },
  { id: "c", key: "souls-proof-c", repo: "https://github.com/ziglang/zig",
    seed: { vibe: "playful, curious, a tinkerer", specialty: "shrinking binary size in systems code", values: ["every byte has to earn its place", "leave notes for the next agent", "collaborate early"], lines: "Likes pairing with other agents; enjoys explaining why something got smaller." } },
];

const client = anthropicClient(await loadModelKey());
const names: string[] = [];
for (const f of ["a", "b", "c"]) {
  const p = join(OUT, `soul-${f}.json`);
  if (existsSync(p)) names.push((JSON.parse(readFileSync(p, "utf8")) as SoulDoc).persona.name);
}
for (const s of SEEDS) {
  if (ONLY && s.id !== ONLY) continue;
  const p = join(OUT, `soul-${s.id}.json`);
  if (existsSync(p) && !ONLY) {
    console.log(`soul ${s.id}: exists (${p}), skipped`);
    continue;
  }
  const spent = laneSpent();
  if (spent + MAX > LANE_CAP_USD) throw new Error(`lane spend ${spent.toFixed(4)} USD + this soul's cap ${MAX} would cross the lane cap ${LANE_CAP_USD}`);
  const agent = key(s.key).id;
  console.log(`soul ${s.id}: agent ${agent}, repo ${s.repo}, cap ${MAX} USD (lane spent so far ${spent.toFixed(4)})`);
  const r = await generateSoul({ seed: s.seed, agent, repo: s.repo, client, maxUsd: MAX, effort: "high", avoidNames: names.filter((n) => n), log: (m) => console.log(`  ${m}`) });
  recordSpend({ what: `generate soul ${s.id} (${s.repo})`, usd: r.usage.usd, calls: r.usage.calls, models: r.usage.models, input_tokens: r.usage.input_tokens + r.usage.cache_read_tokens + r.usage.cache_write_tokens, output_tokens: r.usage.output_tokens, ok: !!r.doc });
  console.log(`  ${r.usage.calls} calls, ${r.usage.usd.toFixed(4)} USD`);
  if (!r.doc) {
    console.log(`  no soul: ${r.problems.join("; ")}`);
    continue;
  }
  if (checkSoul(r.doc).length) throw new Error("generated soul does not check");
  writeFileSync(p, JSON.stringify(r.doc, null, 2) + "\n");
  names.push(r.doc.persona.name);
  console.log(`  ${r.doc.persona.name}: ${r.doc.persona.tagline}\n  digest ${soulDigest(r.doc)}`);
}
console.log(`lane spend total: ${laneSpent().toFixed(4)} USD of ${LANE_CAP_USD}`);
