// Emits onchain/tests/fixtures/merkle.json: payout and usage leaves, roots and proofs built with the
// TypeScript protocol code Core uses (packages/protocol econ.ts and hash.ts). The Rust LiteSVM suite
// claims and debits with them, so a Core-built root is proven to verify onchain.
//   bun onchain/scripts/make-fixtures.ts           write
//   bun onchain/scripts/make-fixtures.ts --check   fail if the committed file differs
import { createPrivateKey, createPublicKey } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { base58Encode, canonicalJson, leafHash, merkleProof, merkleRoot, repoId, verifyProof } from "@lineage/protocol";

const out = new URL("../tests/fixtures/merkle.json", import.meta.url);

/** The ed25519 public key of a 32-byte seed, as solana_keypair::keypair_from_seed derives it. */
function pubkeyOfSeed(byte: number): string {
  const der = Buffer.concat([Buffer.from("302e020100300506032b657004220420", "hex"), Buffer.alloc(32, byte)]);
  const spki = createPublicKey(createPrivateKey({ key: der, format: "der", type: "pkcs8" })).export({ format: "der", type: "spki" });
  return base58Encode(new Uint8Array(spki.subarray(spki.length - 32)));
}

// Seeds shared with onchain/tests (fixture_keys): verifier A, launched agent B, launcher W, plus
// payees that only make the tree deeper.
const A = pubkeyOfSeed(11);
const B = pubkeyOfSeed(12);
const W = pubkeyOfSeed(13);
const extra = [21, 22, 23].map(pubkeyOfSeed);
const EPOCH = 7;

const payouts = [
  { agent: A, dest: `agent:${A}:wallet`, amount: "1234567" },
  { agent: B, dest: `agent:${B}:compute`, amount: "2000000" },
  { agent: B, dest: `agent:${B}:wallet`, amount: "5" },
  { agent: B, dest: `wallet:${W}`, amount: "777" },
  ...extra.map((x, i) => ({ agent: x, dest: `agent:${x}:wallet`, amount: String(1000 + i) })),
].sort((a, b) => (a.agent === b.agent ? (a.dest < b.dest ? -1 : 1) : a.agent < b.agent ? -1 : 1));
const payoutLeaves = payouts.map((p) => leafHash(canonicalJson({ epoch: EPOCH, agent: p.agent, dest: p.dest, amount: p.amount })));
const payoutRoot = merkleRoot(payoutLeaves);

const USAGE_EPOCH = 3;
const usage = [
  { agent: B, amount: "150000", model_tokens: 81234, sandbox_s: 412 },
  { agent: A, amount: "1", model_tokens: 0, sandbox_s: 0 },
  { agent: extra[0]!, amount: "99", model_tokens: 7, sandbox_s: 3 },
];
const usageLeaves = usage.map((u) => leafHash(canonicalJson({ epoch: USAGE_EPOCH, ...u })));
const usageRoot = merkleRoot(usageLeaves);

const doc = {
  _note: "Generated by onchain/scripts/make-fixtures.ts from @lineage/protocol; do not edit.",
  seeds: { A: 11, B: 12, W: 13 },
  keys: { A, B, W },
  payout: {
    epoch: EPOCH,
    root: payoutRoot,
    total: payouts.reduce((s, p) => s + BigInt(p.amount), 0n).toString(),
    leaves: payouts.map((p, i) => ({ ...p, leaf: payoutLeaves[i], proof: merkleProof(payoutLeaves, i) })),
  },
  usage: {
    epoch: USAGE_EPOCH,
    root: usageRoot,
    leaves: usage.map((u, i) => ({ ...u, leaf: usageLeaves[i], proof: merkleProof(usageLeaves, i) })),
  },
  repo: { url: "https://github.com/lineage-test/base58", repo_id: repoId("https://github.com/lineage-test/base58") },
};
for (const l of doc.payout.leaves) if (!verifyProof(l.leaf!, l.proof, payoutRoot)) throw new Error("payout proof");
for (const l of doc.usage.leaves) if (!verifyProof(l.leaf!, l.proof, usageRoot)) throw new Error("usage proof");

const text = JSON.stringify(doc, null, 2) + "\n";
if (process.argv.includes("--check")) {
  if (readFileSync(out, "utf8") !== text) {
    console.error("merkle.json is stale: run bun onchain/scripts/make-fixtures.ts");
    process.exit(1);
  }
  console.log("merkle.json current");
} else {
  writeFileSync(out, text);
  console.log(`wrote ${out.pathname}: ${payouts.length} payout leaves, ${usage.length} usage leaves`);
}
