// Emits onchain/tests/fixtures/msg-seal.json: a body sealed by packages/core seal.ts (the C2
// scheme, SPEC 12.3) to a fixed X25519 key. The LiteSVM suite (tests/tests/msg.rs) posts those
// exact bytes with post_dm and writes the emitted event to tests/fixtures/msg-events.json;
// packages/chain test/msg.test.ts parses that event and opens the body with seal.ts `open`, so the
// round trip TS seal -> program -> event -> TS open is checked end to end.
//   bun onchain/scripts/make-msg-fixtures.ts         write (a new ephemeral key each time)
//   bun onchain/scripts/make-msg-fixtures.ts --check  the committed fixture still opens
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { base58Decode } from "@lineage/protocol";
import { encryptionKeyFromSecret, open, seal } from "../../packages/core/src/seal.ts";

const out = new URL("../tests/fixtures/msg-seal.json", import.meta.url);
const secret = new Uint8Array(32).fill(0x5a);
const key = encryptionKeyFromSecret(secret);
const plaintext = "hello from a lineage agent: shall we split the tokenizer target? reply on the board.";

if (process.argv.includes("--check")) {
  if (!existsSync(out)) throw new Error("no fixture; run without --check");
  const f = JSON.parse(readFileSync(out, "utf8"));
  if (f.recipient_enc_key !== key.public) throw new Error("recipient key changed");
  if (open(f.sealed_b64, key) !== f.plaintext) throw new Error("fixture does not open");
  console.log("msg-seal.json ok");
} else {
  const sealed = seal(plaintext, key.public);
  const doc = {
    _note: "Generated by onchain/scripts/make-msg-fixtures.ts; posted by tests/tests/msg.rs.",
    recipient_secret_hex: Buffer.from(secret).toString("hex"),
    recipient_enc_key: key.public,
    recipient_enc_key_hex: Buffer.from(base58Decode(key.public)).toString("hex"),
    plaintext,
    sealed_b64: sealed,
    sealed_hex: Buffer.from(sealed, "base64").toString("hex"),
  };
  writeFileSync(out, JSON.stringify(doc, null, 2) + "\n");
  console.log(`wrote ${out.pathname} (${Buffer.from(sealed, "base64").length} sealed bytes)`);
}
