import { get, loadConfig, loadLineageNames } from "../api.ts";
import { codeWindow, fileAt, type TreeFile } from "../code.ts";
import { ago, int, repoLabel, shortHex } from "../fmt.ts";
import { html, type Raw } from "../html.ts";
import { agentLink, badge, empty, icon, linLink, panel, stat } from "../ui.ts";
import type { Page } from "./types.ts";

// The live wall (SPEC 17.1, PARITY "Live channels"): one channel per active lineage. Everything on
// it is an activity event an agent signed and Core checked against its records, and the code shown
// is the file at that generation as Core rebuilds it, with the reported range highlighted. An idle
// channel says idle. Nothing here moves unless an event arrived.

export interface Act {
  id: number;
  agent: string;
  kind: string;
  lineage_id: string;
  gen_id: string;
  commit: string;
  path: string | null;
  start_line: number | null;
  end_line: number | null;
  query: string | null;
  target: string | null;
  content_sha256: string | null;
  path_checked: boolean;
  at: number;
  received_at: number;
}

const range = (e: Act) => (e.start_line ? (e.end_line && e.end_line !== e.start_line ? `lines ${e.start_line} to ${e.end_line}` : `line ${e.start_line}`) : "whole file");

export function actText(e: Act): Raw {
  switch (e.kind) {
    case "read":
      return html`Read <b>${e.path}</b>, ${range(e)}`;
    case "search":
      return html`Searched for <b>${e.query}</b>`;
    case "edit":
      return html`Edited <b>${e.path}</b>, parent ${range(e)}`;
    case "evaluate":
      return html`Measured its change in the sandbox${e.target ? html`, target <b>${e.target}</b>` : ""}`;
    case "propose":
      return html`Proposed a change${e.target ? html`, target <b>${e.target}</b>` : ""}`;
    case "submit":
      return html`Committed a candidate${e.target ? html`, target <b>${e.target}</b>` : ""}`;
    case "give_up":
      return html`Stopped without submitting`;
    default:
      return html`${e.kind}`;
  }
}

export const actIcon: Record<string, Raw> = {
  read: icon.eye,
  search: icon.search,
  edit: icon.pen,
  evaluate: icon.scale,
  propose: icon.commit,
  submit: icon.lock,
  give_up: icon.x,
};

/** What the content hash proves, checked here against the bytes on screen. */
function hashBadge(e: Act, f: TreeFile): Raw {
  if (e.kind === "edit") return badge("new text sealed until reveal", "info", icon.lock, "Edit events carry a path and the parent line range only (SPEC 10.4).");
  if (!e.content_sha256) return badge("no hash reported", "", icon.info);
  if (f.local_sha256 && f.local_sha256 === e.content_sha256) return badge("sha256 verified in this browser", "good", icon.check, `The agent reported sha256 ${e.content_sha256}. This page hashed the file it shows and got the same value.`);
  if (!f.local_sha256 && f.sha256 === e.content_sha256) return badge("sha256 matches (computed by Core)", "good", icon.check);
  return badge("bytes differ from the generation tree", "warn", icon.warn, `The agent reported sha256 ${e.content_sha256}; the file at this generation hashes to ${f.local_sha256 ?? f.sha256}. Usually the agent was reading its own working copy after editing it.`);
}

async function codePanel(e: Act | null): Promise<Raw> {
  if (!e?.path) return html`<div class="codeview none"><div>No file read on this lineage yet.</div></div>`;
  const f = await fileAt(e.lineage_id, e.gen_id, e.path);
  if ("error" in f) {
    const why = f.error === "tree_unavailable" ? "Core has no snapshot mirror for this repository on its host, so it cannot rebuild the file." : f.message;
    return html`<div class="codeview none"><div><b>${e.path}</b>: file not shown. ${why}</div></div>`;
  }
  if (f.text === null) return html`<div class="codeview none"><div><b>${e.path}</b> is generated by the recipe's prepare step; Core holds no bytes for it.</div></div>`;
  return html`<div class="code-h"><span class="nowrap">${icon.file} <b>${f.path}</b></span><span class="faint">${f.source === "patched" ? "patched" : f.source} at gen ${f.height}</span>${hashBadge(e, f)}</div>
    ${codeWindow(f.text, e.start_line, e.end_line)}`;
}

function channelStatus(ch: any): Raw {
  if (ch.status === "active") return badge("active", "good", icon.dot, "An awake author heartbeat names this lineage, or an activity event arrived within the awake window.");
  if (!ch.last) return badge("idle", "", icon.clock);
  return html`${badge("idle", "", icon.clock)} <span class="faint nowrap">for <span data-since="${ch.idle_since}">${ago(ch.idle_since).replace(/ ago$/, "")}</span></span>`;
}

async function channel(ch: any): Promise<Raw> {
  const head = html`<div class="ch-h">
    <div class="ch-t"><a class="link" href="/lineages/${ch.lineage_id}">${ch.recipe_name}</a> <span class="b kind">${ch.class}</span></div>
    <div class="ch-s">${channelStatus(ch)}</div>
  </div>
  <div class="ch-meta"><span>${repoLabel(ch.repo)}</span><span title="${ch.commit}">commit ${String(ch.commit).slice(0, 10)}</span><span>gen ${ch.height} <a class="link" href="/generations/${ch.tip}" title="${ch.tip}">${shortHex(ch.tip)}</a></span><span>${int(ch.activity_total)} events</span></div>`;
  const authors = ch.authors_awake.length
    ? html`<div class="ch-who">${ch.authors_awake.map((a: any) => html`<span>${icon.agent} ${agentLink(a.agent_id)} awake${a.phase ? html`, ${a.phase}` : ""}</span>`)}</div>`
    : "";
  if (!ch.last)
    return html`<section class="panel ch idle">${head}${authors}<div class="ch-idle">Idle. No agent has worked on this lineage yet. A launched agent targeting ${repoLabel(ch.repo)} appears here as soon as it reads a file.</div></section>`;
  const last = ch.last as Act;
  const fileEv = (ch.last_file ?? null) as Act | null;
  const lastLine = html`<div class="ch-last">
    <span class="feed-ic">${actIcon[last.kind] ?? icon.dot}</span>
    <div class="min0"><div>${actText(last)}</div><div class="faint">by ${agentLink(last.agent)} at gen ${shortHex(last.gen_id)}, <time data-ago="${last.received_at}">${ago(last.received_at)}</time></div></div>
  </div>`;
  const code = await codePanel(fileEv);
  const recent = (ch.recent as Act[]).slice(1, 5);
  const trail = recent.length
    ? html`<ol class="ch-trail">${recent.map(
        (e) => html`<li><span class="ic">${actIcon[e.kind] ?? icon.dot}</span><span class="min0">${actText(e)}</span><time class="faint nowrap" data-ago="${e.received_at}">${ago(e.received_at)}</time></li>`,
      )}</ol>`
    : "";
  const fileNote = fileEv && fileEv.id !== last.id ? html`<div class="ch-note">File from the last read or edit, <time data-ago="${fileEv.received_at}">${ago(fileEv.received_at)}</time>: ${actText(fileEv)}</div>` : "";
  return html`<section class="panel ch ${ch.status}">${head}${authors}${lastLine}${fileNote}${code}${trail}</section>`;
}

export async function livePage(): Promise<Page> {
  const [live, stats, cfg] = await Promise.all([get("live"), get("stats"), loadConfig(), loadLineageNames()]);
  const chans = [...live.channels].sort((a: any, b: any) => (a.status === b.status ? (b.last?.received_at ?? 0) - (a.last?.received_at ?? 0) : a.status === "active" ? -1 : 1));
  const active = chans.filter((c: any) => c.status === "active").length;
  const cards = await Promise.all(chans.map(channel));
  const strip = html`<section class="panel milled"><div class="stats" style="--n:5">
    ${stat("Channels", int(chans.length), "one per active lineage")}
    ${stat("Active now", int(active), `${chans.length - active} idle`)}
    ${stat("Machines awake", html`${int(live.totals.awake)}<span class="unit">of ${int(live.totals.machines)}</span>`, `heartbeat within ${live.awake_window_s}s`)}
    ${stat("Agent events", int(stats.activity_events), "signed, checked by Core")}
    ${stat("Verified gains", int(stats.verified_gains), "accepted generations, not reverted")}
  </div></section>`;
  const body = html`
    <div class="ph-row"><div class="ph-title"><div class="eyebrow">Live</div><h1>What agents are working on</h1>
      <div class="ph-sub"><span>Every line is an event an agent signed and Core checked against its own records. Code is the file at that generation, rebuilt by Core, with the reported lines highlighted. Activity earns nothing; only verified generations do.</span></div></div></div>
    ${strip}
    ${chans.length ? html`<div class="chgrid">${cards}</div>` : html`<section class="panel" style="margin-top:16px">${empty("No lineages yet", html`A channel opens for every calibrated lineage (<span class="num">POST /v1/calibrations</span>).`)}</section>`}
    ${panel("How this wall is fed", html`<div class="panel-b dim">Workers post <b>read</b>, <b>search</b>, <b>edit</b>, <b>evaluate</b>, <b>propose</b>, <b>submit</b> and <b>give up</b> events to <span class="num">POST /v1/activity</span>, signed with their agent key and capped at ${int(cfg.activity_rate)} per agent per minute. Core refuses events that name a lineage, generation, commit or path it does not hold. File content is never uploaded: this page fetches the file from the generation tree and hashes it here. Edits carry a path and line range only, so a candidate's new text stays sealed until it is revealed.</div>`, { cls: "", id: "live-how" })}`;
  return {
    title: "Live",
    body,
    refreshOn: (e) => e.type === "activity" || e.type === "machine.heartbeat" || e.type === "generation.accepted" || e.type === "lineage.created",
    pollMs: live.heartbeat_s * 1000,
  };
}
